version: '3.8'

services:
  dev:
    container_name: bangsatnyacintapertama-graphql-backend
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
      - "5555:5555"
      - "9229:9229"
    networks:
      - nestjs-network
    volumes:
      - data-volume:/usr/src/app
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
      - redis  # Specify that the dev service depends on both mysql and redis

  mysql:
    image: mysql:latest
    container_name: bangsatnyacintapertama-mysql
    env_file:
      - .env 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  
    networks:
      - nestjs-network
    restart: always

  redis:
    image: redis:latest
    container_name: bangsatnyacintapertama-redis
    ports:
      - "6379:6379"
    networks:
      - nestjs-network
    restart: always

networks:
  nestjs-network:

volumes:
  data-volume:
  mysql-data:
