version: '3.8'

services:
  dev:
    container_name: graphql-backend
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
      - "5555:5555"
      - "9229:9229"
    networks:
      - nestjs-network
    volumes:
      - data-volume:/usr/src/app
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - mysql  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nestjs-network
    restart: always

  mysql: 
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - nestjs-network

networks:
  nestjs-network:

volumes:
  data-volume:
  mysql-data: 
